apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-srv-account
  labels:
    {{- include "plane.commonLabels" $ | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.dockerRegistry.enabled }}
imagePullSecrets:
  - name: {{ .Release.Name }}-docker-registry-credentials
{{- end}}